stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - params.yaml
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
      - params.yaml
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed
      - src/feature_engineering.py
      - params.yaml
    outs:
      - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/features
      - src/model_building.py
      - params.yaml
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - models/model.pkl
      - data/features/test_bow.csv
      - src/model_evaluation.py
      - params.yaml
    outs:
      - evaluation/metrics.json